-- ============================================================================
-- COMPREHENSIVE TRANSLATION KEYS - FINAL VERSION
-- All OnboardingInteractive.tsx, ProfileScreen.tsx, TourContext.tsx translations
-- Uses individual INSERT statements to avoid duplicate key conflicts
-- ============================================================================

-- Common translations
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('common.save', 'en', 'Save', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('common.save', 'sv', 'Spara', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('common.cancel', 'en', 'Cancel', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('common.cancel', 'sv', 'Avbryt', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('common.error', 'en', 'Error', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('common.error', 'sv', 'Fel', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('common.success', 'en', 'Success', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('common.success', 'sv', 'Lyckades', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();

-- OnboardingInteractive.tsx - All step titles and descriptions
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.location.title', 'en', 'Enable Location Access', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.location.title', 'sv', 'Aktivera platsåtkomst', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.location.description', 'en', 'Allow location access to find practice routes near you', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.location.description', 'sv', 'Tillåt platsåtkomst för att hitta övningsrutter nära dig', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.location.enableLocation', 'en', 'Enable Location', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.location.enableLocation', 'sv', 'Aktivera plats', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.location.detectLocation', 'en', 'Detect My Location', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.location.detectLocation', 'sv', 'Hitta min plats', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.location.detectingLocation', 'en', 'Detecting Location...', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.location.detectingLocation', 'sv', 'Hittar plats...', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.location.selectCity', 'en', 'Or Select Your City', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.location.selectCity', 'sv', 'Eller välj din stad', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.location.clearLocation', 'en', 'Clear Selected Location', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.location.clearLocation', 'sv', 'Rensa vald plats', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.location.saveLocation', 'en', 'Save Location & Continue', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.location.saveLocation', 'sv', 'Spara plats & fortsätt', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();

-- OnboardingInteractive.tsx - License Plan step
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.licensePlan.title', 'en', 'Your License Journey', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.licensePlan.title', 'sv', 'Din körkortsresa', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.licensePlan.description', 'en', 'Tell us about your experience level, driving goals and vehicle preferences', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.licensePlan.description', 'sv', 'Berätta om din erfarenhetsnivå, körmål och fordonsval', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.licensePlan.setPreferences', 'en', 'Set My Preferences', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.licensePlan.setPreferences', 'sv', 'Ange mina inställningar', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.licensePlan.savePreferences', 'en', 'Save My Preferences', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.licensePlan.savePreferences', 'sv', 'Spara mina inställningar', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();

-- OnboardingInteractive.tsx - Role step
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.role.title', 'en', 'Select Your Role', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.role.title', 'sv', 'Välj din roll', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.role.description', 'en', 'Are you learning to drive or teaching others?', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.role.description', 'sv', 'Lär du dig köra eller undervisar du andra?', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.role.chooseRole', 'en', 'Choose Role', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.role.chooseRole', 'sv', 'Välj roll', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.role.student', 'en', 'Student', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.role.student', 'sv', 'Elev', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.role.studentDescription', 'en', 'I want to learn to drive', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.role.studentDescription', 'sv', 'Jag vill lära mig köra', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.role.instructor', 'en', 'Instructor', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.role.instructor', 'sv', 'Instruktör', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.role.instructorDescription', 'en', 'I teach others to drive', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.role.instructorDescription', 'sv', 'Jag undervisar andra att köra', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.role.school', 'en', 'Driving School', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.role.school', 'sv', 'Körskola', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.role.schoolDescription', 'en', 'I represent a driving school', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.role.schoolDescription', 'sv', 'Jag representerar en körskola', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.role.saveRole', 'en', 'Save Role & Continue', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.role.saveRole', 'sv', 'Spara roll & fortsätt', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();

-- OnboardingInteractive.tsx - Relationships step
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.relationships.title', 'en', 'Connect with Others', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.relationships.title', 'sv', 'Anslut till andra', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.relationships.description', 'en', 'Connect with instructors or students based on your role', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.relationships.description', 'sv', 'Anslut till instruktörer eller elever baserat på din roll', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.relationships.findConnections', 'en', 'Find Connections', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.relationships.findConnections', 'sv', 'Hitta kontakter', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.relationships.existingTitle', 'en', 'Your Existing Relationships', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.relationships.existingTitle', 'sv', 'Dina befintliga relationer', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.relationships.newConnectionsTitle', 'en', 'New Connection to Add', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.relationships.newConnectionsTitle', 'sv', 'Nya kontakter att lägga till', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.relationships.continueExisting', 'en', 'Continue with Existing Relationships', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.relationships.continueExisting', 'sv', 'Fortsätt med befintliga relationer', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.relationships.addMore', 'en', 'Add More Connections', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.relationships.addMore', 'sv', 'Lägg till fler kontakter', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();

-- OnboardingInteractive.tsx - Complete step
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.complete.title', 'en', 'Ready for Your Journey!', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.complete.title', 'sv', 'Redo för din resa!', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.complete.description', 'en', 'Ready to become a confident driver! Explore the app, progress in exercises, save and upload routes, and discover a community of drivers like you.', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.complete.description', 'sv', 'Redo att bli en säker förare! Utforska appen, gör framsteg i övningar, spara och ladda upp rutter, och upptäck en gemenskap av förare som du.', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.complete.startMyJourney', 'en', 'Start My Journey', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.complete.startMyJourney', 'sv', 'Starta min resa', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.complete.startJourney', 'en', 'Start Using Vromm!', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.complete.startJourney', 'sv', 'Börja använda Vromm!', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();

-- OnboardingInteractive.tsx - Modal titles
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.city.title', 'en', 'Select Your City', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.city.title', 'sv', 'Välj din stad', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.city.searchPlaceholder', 'en', 'Search cities... (try ''Ystad'', ''New York'', etc.)', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.city.searchPlaceholder', 'sv', 'Sök städer... (prova ''Ystad'', ''Stockholm'', etc.)', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.city.noCitiesFor', 'en', 'No cities found for', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.city.noCitiesFor', 'sv', 'Inga städer hittades för', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.city.startTyping', 'en', 'Start typing to search for any city worldwide', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.city.startTyping', 'sv', 'Börja skriva för att söka efter vilken stad som helst världen över', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.vehicle.title', 'en', 'Select Vehicle Type', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.vehicle.title', 'sv', 'Välj fordonstyp', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.transmission.title', 'en', 'Select Transmission', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.transmission.title', 'sv', 'Välj växellåda', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.license.title', 'en', 'Select License Type', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.license.title', 'sv', 'Välj körkortsklass', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.experience.title', 'en', 'Select Experience Level', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.experience.title', 'sv', 'Välj erfarenhetsnivå', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.date.title', 'en', 'When do you want your license?', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.date.title', 'sv', 'När vill du ha ditt körkort?', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();

-- OnboardingInteractive.tsx - Date options
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.date.within3months', 'en', 'Within 3 months', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.date.within3months', 'sv', 'Inom 3 månader', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.date.within6months', 'en', 'Within 6 months', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.date.within6months', 'sv', 'Inom 6 månader', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.date.within1year', 'en', 'Within 1 year', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.date.within1year', 'sv', 'Inom 1 år', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.date.noSpecific', 'en', 'No specific date', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.date.noSpecific', 'sv', 'Inget specifikt datum', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.date.pickSpecific', 'en', 'Pick specific date', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.date.pickSpecific', 'sv', 'Välj specifikt datum', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.date.selectTarget', 'en', 'Select Target Date', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.date.selectTarget', 'sv', 'Välj måldatum', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.date.saveSelectedDate', 'en', 'Save Selected Date', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.date.saveSelectedDate', 'sv', 'Spara valt datum', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();

-- OnboardingInteractive.tsx - Relationship removal modal translations
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.relationships.removeStudentTitle', 'en', 'Remove Student', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.relationships.removeStudentTitle', 'sv', 'Ta bort elev', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.relationships.removeSupervisorTitle', 'en', 'Remove Supervisor', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.relationships.removeSupervisorTitle', 'sv', 'Ta bort handledare', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.relationships.removeStudentConfirm', 'en', 'Are you sure you want to remove {name} as your student?', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.relationships.removeStudentConfirm', 'sv', 'Är du säker på att du vill ta bort {name} som din elev?', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.relationships.removeSupervisorConfirm', 'en', 'Are you sure you want to remove {name} as your supervisor?', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.relationships.removeSupervisorConfirm', 'sv', 'Är du säker på att du vill ta bort {name} som din handledare?', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.relationships.selectConnections', 'en', 'Select Connections', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.relationships.selectConnections', 'sv', 'Välj kontakter', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();

-- Additional relationship description translations
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.relationships.yourSupervisor', 'en', 'Your supervisor', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.relationships.yourSupervisor', 'sv', 'Din handledare', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.relationships.studentYouSupervise', 'en', 'Student you supervise', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.relationships.studentYouSupervise', 'sv', 'Elev du handleder', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.relationships.since', 'en', 'since', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.relationships.since', 'sv', 'sedan', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.connections.tapToRemove', 'en', 'Tap to remove', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.connections.tapToRemove', 'sv', 'Tryck för att ta bort', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();

-- Common Yes/No translations
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('common.yes', 'en', 'Yes', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('common.yes', 'sv', 'Ja', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('common.no', 'en', 'No', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('common.no', 'sv', 'Nej', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();

-- License plan extended fields (already exist but ensuring they're here)
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.licensePlan.hasTheory', 'en', 'Have you passed the theory test?', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.licensePlan.hasTheory', 'sv', 'Har du klarat teoriprovet?', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.licensePlan.hasPractice', 'en', 'Have you passed the practical test?', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.licensePlan.hasPractice', 'sv', 'Har du klarat uppkörningen?', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.licensePlan.previousExperience', 'en', 'Previous driving experience', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.licensePlan.previousExperience', 'sv', 'Tidigare körerfarenhet', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.licensePlan.experiencePlaceholder', 'en', 'Describe your previous driving experience', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.licensePlan.experiencePlaceholder', 'sv', 'Beskriv din tidigare körerfarenhet', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.licensePlan.specificGoals', 'en', 'Specific goals', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.licensePlan.specificGoals', 'sv', 'Specifika mål', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.licensePlan.goalsPlaceholder', 'en', 'Do you have specific goals with your license?', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.licensePlan.goalsPlaceholder', 'sv', 'Har du specifika mål med ditt körkort?', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();

-- Final step language selection
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.complete.selectLanguage', 'en', 'Select Language', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.complete.selectLanguage', 'sv', 'Välj språk', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.complete.languageTitle', 'en', 'Select Language', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.complete.languageTitle', 'sv', 'Välj språk', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();

-- OnboardingInteractive.tsx - Additional dropdown translations
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.date.targetDate', 'en', 'Want my license on', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.date.targetDate', 'sv', 'Vill ha mitt körkort den', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.vehicle.car', 'en', 'Car', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.vehicle.car', 'sv', 'Bil', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();

-- ProgressScreen Paywall Modal Translations (Restored)
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('progressScreen.paywall.title', 'en', 'Premium Learning Path', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('progressScreen.paywall.title', 'sv', 'Premium Lärandeväg', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('progressScreen.paywall.preview', 'en', 'Premium Learning Content', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('progressScreen.paywall.preview', 'sv', 'Premium Lärande Innehåll', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('progressScreen.paywall.includes', 'en', 'This Premium Path Includes:', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('progressScreen.paywall.includes', 'sv', 'Denna Premium Väg Inkluderar:', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('progressScreen.paywall.feature1', 'en', '🎯 Advanced driving exercises', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('progressScreen.paywall.feature1', 'sv', '🎯 Avancerade körövningar', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('progressScreen.paywall.feature2', 'en', '📚 Detailed learning content', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('progressScreen.paywall.feature2', 'sv', '📚 Detaljerat lärande innehåll', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('progressScreen.paywall.feature3', 'en', '🎬 Exclusive video tutorials', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('progressScreen.paywall.feature3', 'sv', '🎬 Exklusiva videotutorials', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('progressScreen.paywall.feature4', 'en', '✅ Progress tracking', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('progressScreen.paywall.feature4', 'sv', '✅ Framstegsspårning', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('progressScreen.paywall.oneTime', 'en', 'one-time unlock', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('progressScreen.paywall.oneTime', 'sv', 'engångslås', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('progressScreen.paywall.lifetime', 'en', 'Lifetime access to this learning path', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('progressScreen.paywall.lifetime', 'sv', 'Livstidsåtkomst till denna lärandeväg', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('progressScreen.paywall.unlock', 'en', 'Unlock Now', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('progressScreen.paywall.unlock', 'sv', 'Lås upp nu', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('progressScreen.paywall.paymentError', 'en', 'Failed to initiate payment', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('progressScreen.paywall.paymentError', 'sv', 'Misslyckades att initiera betalning', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();

-- Stripe Payment Flow Translations (Restored)
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('stripe.processing', 'en', 'Processing Payment', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('stripe.processing', 'sv', 'Behandlar betalning', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('stripe.connecting', 'en', 'Connecting to Stripe payment gateway...', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('stripe.connecting', 'sv', 'Ansluter till Stripe betalningsgateway...', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('stripe.paymentSuccessful', 'en', 'Payment Successful!', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('stripe.paymentSuccessful', 'sv', 'Betalning lyckades!', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('stripe.paymentCancelled', 'en', 'Payment Cancelled', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('stripe.paymentCancelled', 'sv', 'Betalning avbruten', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('stripe.paymentFailed', 'en', 'Payment Failed', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('stripe.paymentFailed', 'sv', 'Betalning misslyckades', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('stripe.initError', 'en', 'Failed to initialize payment', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('stripe.initError', 'sv', 'Misslyckades att initiera betalning', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('stripe.pleaseWait', 'en', 'Please wait...', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('stripe.pleaseWait', 'sv', 'Vänligen vänta...', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('stripe.enterCardDetails', 'en', 'Enter your card details', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('stripe.enterCardDetails', 'sv', 'Ange dina kortuppgifter', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('stripe.securePayment', 'en', 'Secure payment powered by Stripe', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('stripe.securePayment', 'sv', 'Säker betalning med Stripe', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.transmission.manual', 'en', 'Manual', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.transmission.manual', 'sv', 'Manuell', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.license.standardB', 'en', 'Standard License (B)', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.license.standardB', 'sv', 'Standardkörkort (B)', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.experience.beginner', 'en', 'Beginner', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.experience.beginner', 'sv', 'Nybörjare', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.experience.beginnerDescription', 'en', 'Just starting out', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.experience.beginnerDescription', 'sv', 'Precis börjat', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.experience.intermediate', 'en', 'Intermediate', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.experience.intermediate', 'sv', 'Medelnivå', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.experience.intermediateDescription', 'en', 'Some experience', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.experience.intermediateDescription', 'sv', 'Viss erfarenhet', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.experience.advanced', 'en', 'Advanced', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.experience.advanced', 'sv', 'Avancerad', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.experience.advancedDescription', 'en', 'Very experienced', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.experience.advancedDescription', 'sv', 'Mycket erfaren', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();

-- OnboardingInteractive.tsx - Connection modals
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.connections.findInstructors', 'en', 'Find Instructors', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.connections.findInstructors', 'sv', 'Hitta instruktörer', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.connections.findStudents', 'en', 'Find Students', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.connections.findStudents', 'sv', 'Hitta elever', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.connections.findUsers', 'en', 'Find Users', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.connections.findUsers', 'sv', 'Hitta användare', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.connections.searchInstructors', 'en', 'Search for driving instructors to connect with', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.connections.searchInstructors', 'sv', 'Sök efter körinstruktörer att ansluta till', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.connections.searchStudents', 'en', 'Search for students to connect with', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.connections.searchStudents', 'sv', 'Sök efter elever att ansluta till', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.connections.searchUsers', 'en', 'Search for users to connect with', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.connections.searchUsers', 'sv', 'Sök efter användare att ansluta till', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.connections.optionalMessage', 'en', 'Optional message:', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.connections.optionalMessage', 'sv', 'Valfritt meddelande:', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.connections.messagePlaceholder', 'en', 'Add a personal message...', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.connections.messagePlaceholder', 'sv', 'Lägg till ett personligt meddelande...', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.connections.searchPlaceholder', 'en', 'Search by name or email...', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.connections.searchPlaceholder', 'sv', 'Sök efter namn eller e-post...', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.connections.noUsers', 'en', 'No users found', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.connections.noUsers', 'sv', 'Inga användare hittades', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.connections.startTyping', 'en', 'Start typing to search for users', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.connections.startTyping', 'sv', 'Börja skriva för att söka efter användare', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();

-- Common navigation and action buttons
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.skipForNow', 'en', 'Skip for now', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.skipForNow', 'sv', 'Hoppa över för nu', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.maybeLater', 'en', 'Maybe later', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.maybeLater', 'sv', 'Kanske senare', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.continue', 'en', 'Continue', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.continue', 'sv', 'Fortsätt', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();

-- ProfileScreen location translations
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.location.detectingLocation', 'en', 'Detecting Location...', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.location.detectingLocation', 'sv', 'Hittar plats...', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.location.detectLocation', 'en', 'Detect My Location', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.location.detectLocation', 'sv', 'Hitta min plats', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.location.clearLocation', 'en', 'Clear Location', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.location.clearLocation', 'sv', 'Rensa plats', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.location.locationCleared', 'en', 'Location cleared', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.location.locationCleared', 'sv', 'Plats rensad', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.location.selectLocation', 'en', 'Select Your Location', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.location.selectLocation', 'sv', 'Välj din plats', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.location.searchPlaceholder', 'en', 'Search cities... (try ''Stockholm'', ''New York'', etc.)', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.location.searchPlaceholder', 'sv', 'Sök städer... (prova ''Stockholm'', ''Göteborg'', etc.)', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.location.noLocationsFound', 'en', 'No locations found. Keep typing to search worldwide.', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.location.noLocationsFound', 'sv', 'Inga platser hittades. Fortsätt skriva för att söka världen över.', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();

-- ProfileScreen general translations
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.title', 'en', 'Profile', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.title', 'sv', 'Profil', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.avatar.tapToChange', 'en', 'Tap to change avatar', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.avatar.tapToChange', 'sv', 'Tryck för att ändra avatar', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.avatar.changeAvatar', 'en', 'Change Avatar', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.avatar.changeAvatar', 'sv', 'Ändra avatar', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.avatar.chooseFromLibrary', 'en', 'Choose from Library', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.avatar.chooseFromLibrary', 'sv', 'Välj från bibliotek', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.avatar.takePhoto', 'en', 'Take Photo', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.avatar.takePhoto', 'sv', 'Ta foto', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.avatar.removeAvatar', 'en', 'Remove Avatar', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.avatar.removeAvatar', 'sv', 'Ta bort avatar', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.viewProfile', 'en', 'View Profile', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.viewProfile', 'sv', 'Visa profil', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.viewStudent', 'en', 'View Student', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.viewStudent', 'sv', 'Visa elev', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();

-- ProfileScreen tabs
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.tabs.overview', 'en', 'Overview', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.tabs.overview', 'sv', 'Översikt', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.tabs.stats', 'en', 'Stats', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.tabs.stats', 'sv', 'Statistik', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.tabs.relationships', 'en', 'Relationships', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.tabs.relationships', 'sv', 'Relationer', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();

-- ProfileScreen developer tools
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.buttonValue', 'en', 'Developer Tools', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.buttonValue', 'sv', 'Utvecklarverktyg', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.title', 'en', 'Developer Tools', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.title', 'sv', 'Utvecklarverktyg', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.resetOnboardingButton', 'en', 'Reset All Onboarding & Tours', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.resetOnboardingButton', 'sv', 'Återställ all onboarding & turer', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.resetTourButton', 'en', 'Reset Tour Only', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.resetTourButton', 'sv', 'Återställ endast tur', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.resetComplete', 'en', 'Reset Complete', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.resetComplete', 'sv', 'Återställning slutförd', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.tourReset', 'en', 'Tour has been reset. Restart the app to see tour badges again.', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.tourReset', 'sv', 'Tur har återställts. Starta om appen för att se turemblem igen.', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();

-- Tour navigation
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('tour.navigation.previous', 'en', 'Previous', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('tour.navigation.previous', 'sv', 'Föregående', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('tour.navigation.next', 'en', 'Next', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('tour.navigation.next', 'sv', 'Nästa', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('tour.navigation.finish', 'en', 'Finish', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('tour.navigation.finish', 'sv', 'Slutför', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();

-- Tour fallback steps (for TourContext.tsx)
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('tour.fallback.progress.title', 'en', 'Track Your Progress', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('tour.fallback.progress.title', 'sv', 'Följ din utveckling', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('tour.fallback.progress.content', 'en', 'Here you can see your learning progress and complete exercises. Tap the Progress tab to explore learning paths.', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('tour.fallback.progress.content', 'sv', 'Här kan du se dina framsteg och slutföra övningar. Tryck på Framsteg-fliken för att utforska lärningsvägar.', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('tour.fallback.create.title', 'en', 'Create Routes & Events', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('tour.fallback.create.title', 'sv', 'Skapa rutter & evenemang', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('tour.fallback.create.content', 'en', 'Add routes and events here using the central create button. Tap the plus button to get started!', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('tour.fallback.create.content', 'sv', 'Lägg till rutter och evenemang här med den centrala skapa-knappen. Tryck på plus-knappen för att komma igång!', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('tour.fallback.menu.title', 'en', 'Menu & Settings', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('tour.fallback.menu.title', 'sv', 'Meny & inställningar', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('tour.fallback.menu.content', 'en', 'Access your profile, settings, and manage relationships through the menu tab.', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('tour.fallback.menu.content', 'sv', 'Kom åt din profil, inställningar och hantera relationer genom meny-fliken.', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
