-- ============================================================================
-- COPY AND PASTE THIS ENTIRE SCRIPT INTO SUPABASE SQL EDITOR
-- Complete translation keys for OnboardingInteractive.tsx and ProfileScreen.tsx
-- FIXED: Uses individual INSERT statements to avoid duplicate key conflicts
-- ============================================================================

-- Common translations
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('common.save', 'en', 'Save', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('common.save', 'sv', 'Spara', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('common.cancel', 'en', 'Cancel', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('common.cancel', 'sv', 'Avbryt', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('common.error', 'en', 'Error', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('common.error', 'sv', 'Fel', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('common.success', 'en', 'Success', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('common.success', 'sv', 'Lyckades', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('common.remove', 'en', 'Remove', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('common.remove', 'sv', 'Ta bort', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();

-- OnboardingInteractive.tsx location translations
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.location.title', 'en', 'Enable Location Access', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.location.title', 'sv', 'Aktivera platsåtkomst', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.location.description', 'en', 'Allow location access to find practice routes near you', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.location.description', 'sv', 'Tillåt platsåtkomst för att hitta övningsrutter nära dig', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.location.detectLocation', 'en', 'Detect My Location', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.location.detectLocation', 'sv', 'Hitta min plats', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.location.detectingLocation', 'en', 'Detecting Location...', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.location.detectingLocation', 'sv', 'Hittar plats...', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.location.selectCity', 'en', 'Or Select Your City', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.location.selectCity', 'sv', 'Eller välj din stad', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.location.clearLocation', 'en', 'Clear Selected Location', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.location.clearLocation', 'sv', 'Rensa vald plats', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.skipForNow', 'en', 'Skip for now', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.skipForNow', 'sv', 'Hoppa över för nu', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.continue', 'en', 'Continue', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.continue', 'sv', 'Fortsätt', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();

-- OnboardingInteractive.tsx role translations
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.role.title', 'en', 'Select Your Role', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.role.title', 'sv', 'Välj din roll', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.role.description', 'en', 'Are you learning to drive or teaching others?', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.role.description', 'sv', 'Lär du dig köra eller undervisar du andra?', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.role.saveRole', 'en', 'Save Role & Continue', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.role.saveRole', 'sv', 'Spara roll & fortsätt', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();

-- OnboardingInteractive.tsx complete step translations
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.complete.title', 'en', 'Ready for Your Journey!', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.complete.title', 'sv', 'Redo för din resa!', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.complete.startJourney', 'en', 'Start Using Vromm!', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.complete.startJourney', 'sv', 'Börja använda Vromm!', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();

-- City search translations
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.city.title', 'en', 'Select Your City', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.city.title', 'sv', 'Välj din stad', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.city.searchPlaceholder', 'en', 'Search cities... (try ''Ystad'', ''New York'', etc.)', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.city.searchPlaceholder', 'sv', 'Sök städer... (prova ''Ystad'', ''Stockholm'', etc.)', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.city.noCitiesFor', 'en', 'No cities found for', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.city.noCitiesFor', 'sv', 'Inga städer hittades för', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.city.startTyping', 'en', 'Start typing to search for any city worldwide', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('onboarding.city.startTyping', 'sv', 'Börja skriva för att söka efter vilken stad som helst världen över', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();

-- ProfileScreen location translations
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.location.detectingLocation', 'en', 'Detecting Location...', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.location.detectingLocation', 'sv', 'Hittar plats...', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.location.detectLocation', 'en', 'Detect My Location', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.location.detectLocation', 'sv', 'Hitta min plats', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.location.clearLocation', 'en', 'Clear Location', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.location.clearLocation', 'sv', 'Rensa plats', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.location.locationCleared', 'en', 'Location cleared', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.location.locationCleared', 'sv', 'Plats rensad', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.location.selectLocation', 'en', 'Select Your Location', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.location.selectLocation', 'sv', 'Välj din plats', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.location.searchPlaceholder', 'en', 'Search cities... (try ''Stockholm'', ''New York'', etc.)', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.location.searchPlaceholder', 'sv', 'Sök städer... (prova ''Stockholm'', ''Göteborg'', etc.)', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();

-- ProfileScreen general translations
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.title', 'en', 'Profile', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.title', 'sv', 'Profil', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.avatar.tapToChange', 'en', 'Tap to change avatar', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.avatar.tapToChange', 'sv', 'Tryck för att ändra avatar', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.viewProfile', 'en', 'View Profile', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.viewProfile', 'sv', 'Visa profil', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.viewStudent', 'en', 'View Student', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.viewStudent', 'sv', 'Visa elev', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();

-- Tour navigation translations
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('tour.navigation.previous', 'en', 'Previous', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('tour.navigation.previous', 'sv', 'Föregående', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('tour.navigation.next', 'en', 'Next', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('tour.navigation.next', 'sv', 'Nästa', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('tour.navigation.skip', 'en', 'Skip', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('tour.navigation.skip', 'sv', 'Hoppa över', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('tour.navigation.close', 'en', 'Close', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('tour.navigation.close', 'sv', 'Stäng', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('tour.navigation.finish', 'en', 'Finish', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('tour.navigation.finish', 'sv', 'Slutför', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();

-- Tour fallback step translations
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('tour.fallback.progress.title', 'en', 'Track Your Progress', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('tour.fallback.progress.title', 'sv', 'Följ din utveckling', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('tour.fallback.progress.content', 'en', 'Here you can see your learning progress and complete exercises. Tap the Progress tab to explore learning paths.', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('tour.fallback.progress.content', 'sv', 'Här kan du se dina framsteg och slutföra övningar. Tryck på Framsteg-fliken för att utforska lärningsvägar.', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('tour.fallback.create.title', 'en', 'Create Routes & Events', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('tour.fallback.create.title', 'sv', 'Skapa rutter & evenemang', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('tour.fallback.create.content', 'en', 'Add routes and events here using the central create button. Tap the plus button to get started!', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('tour.fallback.create.content', 'sv', 'Lägg till rutter och evenemang här med den centrala skapa-knappen. Tryck på plus-knappen för att komma igång!', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('tour.fallback.menu.title', 'en', 'Menu & Settings', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('tour.fallback.menu.title', 'sv', 'Meny & inställningar', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('tour.fallback.menu.content', 'en', 'Access your profile, settings, and manage relationships through the menu tab.', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('tour.fallback.menu.content', 'sv', 'Kom åt din profil, inställningar och hantera relationer genom meny-fliken.', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();

-- Developer tools translations
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.title', 'en', 'Developer Tools', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.title', 'sv', 'Utvecklarverktyg', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.resetComplete', 'en', 'Reset Complete', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.resetComplete', 'sv', 'Återställning slutförd', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.tourReset', 'en', 'Tour has been reset. Restart the app to see tour badges again.', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.tourReset', 'sv', 'Tur har återställts. Starta om appen för att se turemblem igen.', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.testPromotional', 'en', 'Test', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.testPromotional', 'sv', 'Test', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.testPromotionalMessage', 'en', 'Promotional modal trigger sent - check console and UI.', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.testPromotionalMessage', 'sv', 'Kampanjmodal utlöst - kolla konsol och UI.', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.debugModeTitle', 'en', 'Debug Mode', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.debugModeTitle', 'sv', 'Felsökningsläge', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.debugEnabled', 'en', 'Visual debugging enabled - components now show borders and dimensions', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.debugEnabled', 'sv', 'Visuell felsökning aktiverad - komponenter visar nu kanter och dimensioner', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.debugDisabled', 'en', 'Visual debugging disabled', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.debugDisabled', 'sv', 'Visuell felsökning inaktiverad', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();

-- Essential core translations for immediate use
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.fullName', 'en', 'Full Name', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.fullName', 'sv', 'Fullständigt namn', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.location', 'en', 'Location', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.location', 'sv', 'Plats', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.signOut', 'en', 'Sign Out', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.signOut', 'sv', 'Logga ut', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();

-- Profile tabs translations
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.tabs.overview', 'en', 'Overview', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.tabs.overview', 'sv', 'Översikt', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.tabs.stats', 'en', 'Stats', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.tabs.stats', 'sv', 'Statistik', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.tabs.relationships', 'en', 'Relationships', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.tabs.relationships', 'sv', 'Relationer', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();

-- RelationshipManagementModal key translations
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('relationships.invitationSent', 'en', 'Invitation Sent!', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('relationships.invitationSent', 'sv', 'Inbjudan skickad!', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('relationships.invitationSentMessage', 'en', 'An invitation has been sent. They will need to accept it before the relationship is created.', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('relationships.invitationSentMessage', 'sv', 'En inbjudan har skickats. De behöver acceptera den innan relationen skapas.', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('relationships.invitationAccepted', 'en', 'Invitation accepted! Relationship created.', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('relationships.invitationAccepted', 'sv', 'Inbjudan accepterad! Relation skapad.', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('relationships.invitationDeclined', 'en', 'Invitation declined', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('relationships.invitationDeclined', 'sv', 'Inbjudan avböjd', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('relationships.invitationCancelled', 'en', 'Invitation cancelled', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('relationships.invitationCancelled', 'sv', 'Inbjudan avbruten', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();

-- ProfileScreen Avatar Modal translations
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.avatar.changeAvatar', 'en', 'Change Avatar', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.avatar.changeAvatar', 'sv', 'Ändra avatar', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.avatar.chooseFromLibrary', 'en', 'Choose from Library', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.avatar.chooseFromLibrary', 'sv', 'Välj från bibliotek', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.avatar.takePhoto', 'en', 'Take Photo', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.avatar.takePhoto', 'sv', 'Ta foto', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.avatar.removeAvatar', 'en', 'Remove Avatar', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.avatar.removeAvatar', 'sv', 'Ta bort avatar', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();

-- ProfileScreen Location Sheet translations  
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.location.noLocationsFound', 'en', 'No locations found. Keep typing to search worldwide.', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.location.noLocationsFound', 'sv', 'Inga platser hittades. Fortsätt skriva för att söka världen över.', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();

-- ProfileScreen Developer Tools Button translations
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.buttonValue', 'en', 'Developer Tools', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.buttonValue', 'sv', 'Utvecklarverktyg', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.resetOnboardingButton', 'en', 'Reset All Onboarding & Tours', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.resetOnboardingButton', 'sv', 'Återställ all onboarding & turer', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.resetTourButton', 'en', 'Reset Tour Only', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.resetTourButton', 'sv', 'Återställ endast tur', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.startTourButton', 'en', 'Start Database Tour', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.startTourButton', 'sv', 'Starta databastur', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.resetProgressButton', 'en', 'Reset Learning Progress', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.resetProgressButton', 'sv', 'Återställ inlärningsframsteg', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.resetRoutesButton', 'en', 'Reset All Routes', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.resetRoutesButton', 'sv', 'Återställ alla rutter', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.resetCommentsButton', 'en', 'Reset Comments & Reviews', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.resetCommentsButton', 'sv', 'Återställ kommentarer & recensioner', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.resetEventsButton', 'en', 'Reset Events & Messages', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.resetEventsButton', 'sv', 'Återställ händelser & meddelanden', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.nuclearResetButton', 'en', 'Nuclear Reset (Everything)', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.nuclearResetButton', 'sv', 'Totalåterställning (allt)', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.refreshTranslationsButton', 'en', 'Refresh Translations', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.refreshTranslationsButton', 'sv', 'Uppdatera översättningar', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.testPromotionalButton', 'en', 'Test Promotional Modal', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.testPromotionalButton', 'sv', 'Testa kampanjmodal', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.contentDemoButton', 'en', 'Content Updates Demo', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.contentDemoButton', 'sv', 'Demo för innehållsuppdateringar', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.translationDemoButton', 'en', 'Translation Demo', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.translationDemoButton', 'sv', 'Översättningsdemo', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.debugModeButton', 'en', 'Toggle Debug Mode', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('profile.developerTools.debugModeButton', 'sv', 'Växla felsökningsläge', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();

-- LicensePlanScreen translations
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('licensePlan.title', 'en', 'Your License Plan', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('licensePlan.title', 'sv', 'Din körkortsplan', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('licensePlan.description', 'en', 'Tell us about yourself and your goals', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('licensePlan.description', 'sv', 'Berätta om dig och dina mål', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('licensePlan.helpText', 'en', 'Help us customize your license plan by answering a few questions.', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('licensePlan.helpText', 'sv', 'Hjälp oss anpassa din körkortsplan genom att svara på några frågor.', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('licensePlan.targetDateQuestion', 'en', 'When do you want to get your license?', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('licensePlan.targetDateQuestion', 'sv', 'När vill du ta körkort?', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('licensePlan.selectDate', 'en', 'Select Date', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('licensePlan.selectDate', 'sv', 'Välj datum', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('licensePlan.theoryQuestion', 'en', 'Have you passed the theory test?', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('licensePlan.theoryQuestion', 'sv', 'Har du klarat teoriprovet?', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('licensePlan.practiceQuestion', 'en', 'Have you passed the practical test?', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('licensePlan.practiceQuestion', 'sv', 'Har du klarat uppkörningen?', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('licensePlan.yes', 'en', 'Yes', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('licensePlan.yes', 'sv', 'Ja', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('licensePlan.no', 'en', 'No', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('licensePlan.no', 'sv', 'Nej', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('licensePlan.previousExperience', 'en', 'Previous driving experience', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('licensePlan.previousExperience', 'sv', 'Tidigare körerfarenhet', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('licensePlan.experiencePlaceholder', 'en', 'Describe your previous driving experience', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('licensePlan.experiencePlaceholder', 'sv', 'Beskriv din tidigare körerfarenhet', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('licensePlan.specificGoals', 'en', 'Specific goals', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('licensePlan.specificGoals', 'sv', 'Specifika mål', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('licensePlan.goalsPlaceholder', 'en', 'Do you have specific goals with your license?', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('licensePlan.goalsPlaceholder', 'sv', 'Har du specifika mål med ditt körkort?', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('licensePlan.saving', 'en', 'Saving...', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('licensePlan.saving', 'sv', 'Sparar...', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('licensePlan.saveButton', 'en', 'Save License Plan', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
INSERT INTO translations (key, language, value, platform, created_at, updated_at) VALUES ('licensePlan.saveButton', 'sv', 'Spara körkortsplan', 'mobile', NOW(), NOW()) ON CONFLICT (key, language, platform) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
